### ISSUE TITLE
Hide metrics-export-prometheus dependency under a feature flag

### ISSUE THREAD

**Issue by xDarksome** [Ptrskay3/axum-prometheus#16]
This crate is currently doing 2 things: collecting metrics via `metrics` crate and exporting them via `metrics-export-prometheus`.
It would be great if we could use only the collecting part separately without requirement to compile `prometheus` related code.

As an alternative, consider extracting collection functionality into a separate crate. (ex. `axum-metrics`)

**Comment by Ptrskay3** [comment]
Seems like a good idea. 
How important would be this feature for you? As of now, I don't have the capacity to implement this in the near future. :disappointed:

**Comment by xDarksome** [comment]
It's not particularly important for me, currently. Just wanted it to be here for future refactorings.

**Comment by AlJohri** [comment]
We would also be interested in potentially using these metrics with a different exporter, such as Cloudwatch via [metrics_cloudwatch](https://github.com/ramn/metrics_cloudwatch) or [metrics_cloudwatch_embedded](https://github.com/BMorinDrifter/metrics-cloudwatch-embedded).

**Comment by Ptrskay3** [comment]
Just released `0.4.0`, that hides Prometheus related stuff behind the `prometheus` feature flag, which is enabled by default, and allows using other exporters. For details, see the updated documentation.
