### ISSUE TITLE
Please create a new release to fix `cargo audit` RUSTSEC-2020-0168

### ISSUE THREAD

**Issue by Logarithmus** [Ptrskay3/axum-prometheus#21]
https://rustsec.org/advisories/RUSTSEC-2020-0168
You already use new `metrics-exporter-prometheus 0.12.0` in `master` branch, so you only need to create a new release

**Comment by Ptrskay3** [comment]
Released `0.3.3` that uses `metrics-exporter-prometheus = 0.12`.
