### ISSUE TITLE
0.3.3 breaks additional metrics

### ISSUE THREAD

**Issue by rthomas** [Ptrskay3/axum-prometheus#23]
With the `0.3.3` update, this breaks additional metrics being included in the prometheus output. In `0.3.2` we can use the `metrics` crate, `gauge!` and `counter!` metrics to have these included in the final output, which is not the case anymore.

Forcing `=0.3.2` fixes this for us.

**Comment by Ptrskay3** [comment]
The only difference between `0.3.2` and `0.3.3` is the update to `metrics=0.21` and `metrics-exporter-prometheus=0.12`. Are you using those updated versions (or through the re-export from this crate)? If that's the case, I'm guessing the issue is not in axum_prometheus.

**Comment by rthomas** [comment]
Yep you were right, thanks! Updating to `metrics=0.21` fixed this for us.
