### ISSUE TITLE
Consider using std::sync::OnceLock over use once_cell::sync::OnceCell

### ISSUE THREAD

**Issue by FalkWoldmann** [Ptrskay3/axum-prometheus#30]
Since Rust version 1.70 there is the thread-safe [std::sync::OnceLock](https://doc.rust-lang.org/stable/std/sync/struct.OnceLock.html) struct, which could replace once_cell::sync::OnceCell and thus reduce the external dependencies.

**Comment by Ptrskay3** [comment]
Yes, this is true, however I'd rather not bump MSRV to 1.70, since it's relatively new, and I don't want to force people into an upgrade.
