### ISSUE TITLE
Inconsistent PrometheusHandle export

### ISSUE THREAD

**Issue by rillian** [Ptrskay3/axum-prometheus#38]
The crate exports an `axum_prometheus::Handle` type, which wraps `metrics_exporter_prometheus::PrometheusHandle`. However, `PrometheusMetricLayer::pair()` returns a `PrometheusHandle` directly. As far as I can tell, that means the return type of this public function isn't actually visible, and one can't pass it to a helper function, for example, without importing it separately through a direct dependency on `metrics_exporter_prometheus`.

Would it be possible to
```rust
pub use metrics_exporter_prometheus::PrometheusHandle;
```
so API clients could obtain the correct type directly from this crate?

**Comment by Ptrskay3** [comment]
I believe we have it, so it should be possible what you're asking.

https://github.com/Ptrskay3/axum-prometheus/blob/4601af8fd57e82c69485a78c2750fb2e1688c61a/src/lib.rs#L210-L211

**Comment by rillian** [comment]
Oh, as in
```rust
use axum_prometheus::metrics_exporter_prometheus::PrometheusHandle;     
```
Yes, that does work. Thanks!

I do still think it would be less surprising to export `PrometheusHandle` immediately under the `axum_prometheus` namespace, since it's a return type of a public function. And shorter. :)

**Comment by Ptrskay3** [comment]
Thanks for the suggestion, I think I'll keep it as-is for now, because the documentation [re-exports section](https://docs.rs/axum-prometheus/latest/axum_prometheus/#reexports) shows it clearly enough in my opinion.
