### ISSUE TITLE
Use Content-Length HTTP header when possible for body size

### ISSUE THREAD

**Issue by BaptisteRoseau** [Ptrskay3/axum-prometheus#53]
As specified in the [documentation](https://docs.rs/axum-prometheus/latest/axum_prometheus/struct.MetricLayerBuilder.html#method.enable_response_body_size), the body size computation can introduce performance overhead, supposedly because the body is consumed to be measured.

A proposition to avoid to avoid this performance overhead could be to use the `Content-Length` or `Transfer-Encoding` HTTP header when it is provided to avoid having to actually consume and measure the body.

Sure, it can be inexact in crafted packets, but I believe the tradeoff between the exactitude of the data and the performance overhead is worth it. Or at least, it may allow the measure of the body by default, and add an option if we want to consume the body instead of relying on the header (as it is currently done in the builder).

Now, what happens if the header is not defined: I don't know. We could either:

- Use a body size of 0
- Not record the event
- Consume the body

I love this crate btw <3

**Comment by Ptrskay3** [comment]
The documentation lacks some details here, probably it needs to be updated at some point. The overhead comes from the fact that we need to construct/update the histogram on every request, and not (necessarily) the body size calculation.

In fact, we already use [`http_body::Body::size_hint`](https://docs.rs/http-body/latest/http_body/trait.Body.html#method.size_hint), or if it's not given the `Content-Length` header.
https://github.com/Ptrskay3/axum-prometheus/blob/aaf0a29215837a9bab10e9af3dd216a01d3c76ee/src/lifecycle/body.rs#L43-L48

**Comment by BaptisteRoseau** [comment]
Oh, my bad then.

I had looked up in the code to validate or not my assumptions, but not deep enough it seems.

Thank you for your quick answer, I will close this issue.
