### ISSUE TITLE
`Failed to set global recorder: SetRecorderError { .. }` when using `axum-test`

### ISSUE THREAD

**Issue by Tanguille** [Ptrskay3/axum-prometheus#64]
First and foremost thanks for the nice crate. It works as expected. 

The issue I'm reporting is only concerning my integration tests which output the following error: `/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-prometheus-0.7.0/src/lib.rs:852:48:
Failed to set global recorder: SetRecorderError { .. }`.

Is there a way to disable setting the recorder for testing or another recommended way to resolve this?

**Comment by Ptrskay3** [comment]
Something similar came up recently in https://github.com/Ptrskay3/axum-prometheus/issues/59. What do you think about the solutions I mentioned there? (Let's note that `BaseMetricLayer` is available since 0.7.0)

**Comment by Tanguille** [comment]
Since I don't need metrics in tests I wouldn't mind removing that layer for the test but I don't know an elegant way to do this. I tried implementing `BaseMetricLayer` via [this example](https://github.com/Ptrskay3/axum-prometheus/blob/master/examples/base-metric-layer-example/src/main.rs). However I can only see my custom `metrics` and not the predefined ones from this crate. Is it not possible to use both?  

![image](https://github.com/user-attachments/assets/6a18cf2e-26fa-4e45-8a4f-1105f481cb18)

My code: 
```rs
use axum_prometheus::{metrics_exporter_prometheus::PrometheusBuilder, BaseMetricLayer};
use metrics_util::MetricKindMask;
use std::net::{IpAddr, Ipv4Addr, SocketAddr};
use std::time::Duration;

pub struct Metric {
    pub name: &'static str,
    pub description: &'static str,
}

pub const CONCURRENT_USERS: Metric = Metric {
    name: "concurrent_users",
    description: "This metric tracks the number of concurrent users, defined as the number of session that made a request in the last five minutes",
};

pub const GAUGES: [Metric; 1] = [CONCURRENT_USERS];

pub fn metrics(port: &u16) {
    println!("initializing metrics exporter");

    PrometheusBuilder::new()
        .idle_timeout(
            MetricKindMask::COUNTER | MetricKindMask::HISTOGRAM,
            Some(Duration::from_secs(10)),
        )
        .with_http_listener(SocketAddr::new(
            IpAddr::V4(Ipv4Addr::new(0, 0, 0, 0)),
            port.to_owned(),
        ))
        .install()
        .expect("failed to install Prometheus recorder");

    for name in GAUGES {
        register_gauge(name)
    }
}

let prometheus_layer = utils::create::metrics(&3002);

 let app = configure_router(app_state.clone())
        .with_state(app_state)
        .route("/fast", get(|| async {}))
        .route(
            "/slow",
            get(|| async {
                tokio::time::sleep(std::time::Duration::from_secs(1)).await;
            }),
        )
        .layer(prometheus_layer)
        .layer(session_manager_layer)
        .layer(TraceLayer::new_for_http())
        .layer(localisation_service)
        .layer(axum::extract::DefaultBodyLimit::max(
            constants::MULTIPART_SIZE_LIMIT,
        ))
        .nest_service("/assets", get_service(ServeDir::new("assets")))
        .nest_service("/style", get_service(ServeDir::new("style")))
        .nest_service("/scripts", get_service(ServeDir::new("scripts")))
        .layer(BaseMetricLayer::new());
```

**Comment by Ptrskay3** [comment]
> Is it not possible to use both?

It's definitely possible.

From first glance in that example I see both
```rust
let prometheus_layer = utils::create::metrics(&3002);
// cut ..
.layer(prometheus_layer)
```
and 
```rust
 .layer(BaseMetricLayer::new());
```

I don't know what `utils::create::metrics` is doing, but this look suspicious. If you use `BaseMetricLayer`, you don't need to add any other layers related to this crate.

In case this doesn't fix the issue, then unfortunately I can't really tell what else may be wrong without creating a reproducible example myself then trying it. I think I'll definitely invest some time into improving the testing experience, because from the recent issues it semms this crate doesn't have a great story when it comes to testing.

**Comment by Tanguille** [comment]
Thank you very much for this personalized example! Now I can see all metrics as expected but am still experiencing some issues with tests. Even tho nothing is running on the specified ports (3000 for server, 3002 for metrics) it's outputting that the address is already in use. Any idea on how to resolve this? 
![image](https://github.com/user-attachments/assets/0f4eecb6-e10e-4389-8030-c6afd6990c82)

**Comment by Tanguille** [comment]
I fixed it by re-reading the other issue you referenced before and implementing `INIT.call_once`. Thanks for the help!

Here is my init function for future reference:
```rs
pub fn init(port: &u16) {
    INIT.call_once(|| {
        PrometheusBuilder::new()
            .with_http_listener(SocketAddr::new(
                IpAddr::V4(Ipv4Addr::new(0, 0, 0, 0)),
                port.to_owned(),
            ))
            .install()
            .expect("failed to install Prometheus recorder");

        for name in &GAUGES {
            register_gauge(name);
        }
    });
}
```

**Comment by Ptrskay3** [comment]
Great! I'll open an issue regardless, since I think enough people complained about this before. #65
