### ISSUE TITLE
axum_http_requests_pending metric leak 

### ISSUE THREAD

**Issue by m-ronchi** [Ptrskay3/axum-prometheus#7]
Hi,

I noticed that the metric `axum_http_requests_pending` does not get properly decremented when the client connection is aborted, so its value may increase over time.

I can reproduce with this test:
```
use axum::{routing::get, Router};
use axum_prometheus::PrometheusMetricLayer;
use tokio::{
    select,
    time::{sleep, Duration},
};

#[tokio::test]
async fn metrics_socket() {
    let (metrics, prom) = PrometheusMetricLayer::pair();
    let app: Router = Router::new()
        .route(
            "/test",
            get(|| async { sleep(Duration::from_millis(10)).await }),
        )
        .layer(metrics);

    assert_eq!(prom.render(), "");

    let (tx, rx) = tokio::sync::oneshot::channel();
    let server = tokio::spawn(async {
        axum::Server::bind(&([127, 0, 0, 1], 3000).into())
            .serve(app.into_make_service())
            .with_graceful_shutdown(async {
                rx.await.unwrap();
            })
            .await
            .unwrap();
    });

    select! {
        r = reqwest::get("http://localhost:3000/test") => {r.unwrap();},
        _ = sleep(Duration::from_millis(10)) => (),
    }

    sleep(Duration::from_millis(10)).await;
    assert_eq!(
        prom.render()
            .lines()
            .filter(|l| l.starts_with("axum_http_requests_pending"))
            .map(|l| l.split(" ").last().unwrap())
            .collect::<String>(),
        "0"
    );
    tx.send(()).unwrap();
    server.await.unwrap();
}

```

or by stress-testing with `autocannon` and observing the metric value is not 0 after it ends

(also the `axum_http_requests_duration_seconds` histogram is not updated, but i'm unsure which should be the correct behaviour for aborted requests here)

**Comment by Ptrskay3** [comment]
Yes, I noticed this too wrt aborted connections in the past. With your provided example I can't really reproduce it though. 

For the requests pending metric probably the current design is flawed, and I think there's room for exploration. I'm curios how  `InFlightRequest` middleware from `tower_http` behaves.. something similar to that might solve it. I'll be experimenting with this when I find the time.
